### PR TITLE
Bugfix/#12 android always true

### LINKED ISSUE #12: wifi connect to non existing network returns true
I connect to this network:

image

It does not exist in my area. But I still get `true` when using WifiConnector.connectToWifi

### PR DESCRIPTION
**Pull request by vanlooverenkoen**
Fixed #12 

After taking a look at the android documentation if the wifi network could not be found -1 is used. this was not yet checked in the plugin code

### CODE REVIEW

**Comment by SaltySpaghetti** [comment]
It happens to be `true` also with wrong password. It doesn't matter what do you pass to `.connectToWifi()`, it returns always true with unexisting SSID and wrong password

**Comment by vanlooverenkoen** [comment]
@SaltySpaghetti even with this pull request?

**Comment by SaltySpaghetti** [comment]
Exactly. I ran this code
```dart
log('Started', name: 'State');
var success = await WifiConnector.connectToWifi(
  ssid: "AbsolutelyNonExistingNetwork", 
  password: 'AbsolutelyNonExistingPassword'
);

log('$success', name: 'Success');
log('Finished', name: 'State');
```

And this is the result in console
```bash
[State] Started
[Success] true
[State] Finished
```

**Comment by vanlooverenkoen** [comment]
Hmm alright I will check/fix it tomorrow.

**Comment by SaltySpaghetti** [comment]
As I said earlier, there's a problem either with non existing SSID and wrong password. The result is `true` with both cases.

**Comment by vanlooverenkoen** [comment]
Hmm strange. When I test this I get `false`. But with your testcase I do get `true` indeed.
```
    print('Started');
    var success = await WifiConnector.connectToWifi(
        ssid: "unknown",
        password: 'unknown'
    );
    print('$success');
    print('Finished');
```

**Comment by wonjerry** [comment]
I think it's a timing issue. Referring to this [link](https://stackoverflow.com/questions/8818290/how-do-i-connect-to-a-specific-wi-fi-network-in-android-programmatically), it's better to revert to the old version of the code. addNetwork and find ssid from configuredNetworks

```kotlin
      addNetwork(wifiConfiguration)
      configuredNetworks.find { network ->
        network.SSID == wrapWithDoubleQuotes(ssid)
      }?.let { network ->
        disconnect()
        enableNetwork(network.networkId, true)
        reconnect()
        result.success(true)
      } ?: let {
        result.success(false)
      }
```

**Comment by vanlooverenkoen** [comment]
The moment I use a password with more than 8 chars I always get connected true.

**Comment by vanlooverenkoen** [comment]
> 

This simplified version should also work. 
https://stackoverflow.com/a/20504821/5115254

But indeed the previous implementation had no issues with this. I will revert it.

**Review by wonjerry — APPROVED** [review]
Thank you for your work

**Comment by vanlooverenkoen** [comment]
A colleague of mine still found an issue.
I will check again today

**Comment by SaltySpaghetti** [comment]
Sorry to bother you all, but I'm not skilled enough in native android sintax. The usage in Dart is going to be the same?

**Comment by wonjerry** [comment]
Yes. It doesn't affect what you use in your dart. It is the same as the method used previously.

**Comment by vanlooverenkoen** [comment]
@wonjerry are you sure the previous implementation worked for pre 2.0.0? Because my `configuredNetworks` are always empty

**Comment by vanlooverenkoen** [comment]
> Sorry to bother you all, but I'm not skilled enough in native android syntax. The usage in Dart is going to be the same?

Indeed the dart API will not change.

**Comment by vanlooverenkoen** [comment]
> @wonjerry are you sure the previous implementation worked for pre 2.0.0? Because my `configuredNetworks` are always empty

https://developer.android.com/reference/android/net/wifi/WifiManager#getConfiguredNetworks()

this is deprecated starting from API level 29. Makes sense it is always empty. I will create a system that supports all API levels. And I will finish that today.

**Comment by vanlooverenkoen** [comment]
The new api for wifi connection is completely different and requires permission checks. I am adding these permission check & request methods to the API of this plugin so it is easy to use.

**Comment by SaltySpaghetti** [comment]
@vanlooverenkoen man, you are the best!

**Comment by vanlooverenkoen** [comment]
image
HAHAH that explains :D

**Comment by vanlooverenkoen** [comment]
For my application I don't need internet so I will also add a field `internetRequired` so we can make the correct switch in the native part. (Android only) `internetRequired` will be true by default

**Comment by SaltySpaghetti** [comment]
> image
> HAHAH that explains :D 

Why would you do this? Maybe to get a LAN connection?

**Comment by vanlooverenkoen** [comment]
> > image
> > HAHAH that explains :D
> 
> Why would you do this? Maybe to get a LAN connection?

We are building an app that configures a hardware device over wifi without internet connectivity. We should communicate with the gateway itself that has an API that can be accessed over the local network.

**Comment by SaltySpaghetti** [comment]
> We are building an app that configures a hardware device over wifi without internet connectivity. We should communicate with the gateway itself that has an API that can be accessed over the local network.

Oh I see.

**Comment by vanlooverenkoen** [comment]
And along the way you can see me struggling in this thread 😂

**Comment by SaltySpaghetti** [comment]
Just to know, when will this be merged? No pressure, I don't need it immediately, just asking.

**Comment by vanlooverenkoen** [comment]
> 

We needed it yesterday so I will be working on this until it is merged. Or otherwise I will use my personal branch. But I will update this pull request once I have a working version

**Comment by vanlooverenkoen** [comment]
Alright I getting there

**Comment by vanlooverenkoen** [comment]
I have finished the implementation. 
With Internet:
**<= Android 9**
-  old implementation

**Android 10**
- suggest a new network -> https://developer.android.com/guide/topics/connectivity/wifi-suggest (In the end your OS will choose if the network will be chosen or not)

**>= Android 11**
- Request to add a network to your saved networks. User should still allow this.  -> https://developer.android.com/reference/android/provider/Settings#ACTION_WIFI_ADD_NETWORKS (in the end your OS will still choose if that wifi should be used or not)

------------------------------------------------------------------------------------------------------------------------

Without internet
**<= Android 9**
-  old implementation (internet could still be possible)

**>= Android 10**
- OS searches for that specific wifi network. User should still allow this.  -> https://developer.android.com/guide/topics/connectivity/wifi-bootstrap (no internet is possible)

**Comment by vanlooverenkoen** [comment]
@wonjerry & @SaltySpaghetti is it possible to test this pr as well?

**Comment by SaltySpaghetti** [comment]
I'm gonna try it this afternoon

**Comment by vanlooverenkoen** [comment]
There are some breaking changes. we now have a `securityType` that replaces `isWep` so we can easily specify `wap2` & `wap3`

**Comment by SaltySpaghetti** [comment]
> Exactly.
> 
> I ran this code:
> 
> ```dart
> log('Started', name: 'State');
> var success = await WifiConnector.connectToWifi(
>   ssid: "AbsolutelyNonExistingNetwork", 
>   password: 'AbsolutelyNonExistingPassword'
> );
> 
> log('$success', name: 'Success');
> log('Finished', name: 'State');
> ```
> 
> and this is the result in console:
> 
> ```shell
> [State] Started
> [Success] true
> [State] Finished
> ```

@vanlooverenkoen I've executed the same code as before and still getting the same scenario.

**Comment by vanlooverenkoen** [comment]
> @vanlooverenkoen I've executed the same code as before and still getting the same scenario.

What Android version are you using? And can you confirm if the pre 2.0.0 release worked on your device? Because right now it is just exactly the same implementation as 2.0.0

**Comment by SaltySpaghetti** [comment]
I'm testing on Android 9 and I can't upgrade it. By 6th Dec I'll have a phone with Android 11 and I can test both versions for you.

**Comment by vanlooverenkoen** [comment]
Alright yes so Android 9 will still use the same implementation as yesterday. For now I did the full refactor of android 10 and above

**Comment by SaltySpaghetti** [comment]
> Alright yes so Android 9 will still use the same implementation as yesterday. For now I did the full refactor of android 10 and above

Oh ok, sorry. I didn't understand that the update was only for Android 10+. My bad

**Comment by SaltySpaghetti** [comment]
@vanlooverenkoen I found out that my neighbour has Android 11. I'm gonna bother her!

**Comment by SaltySpaghetti** [comment]
Tested on Android 10 and 11 and still getting true.

**Comment by vanlooverenkoen** [comment]
Hmm it is a lot more complex on >9 than I thought. The Android API is quite bad, so after you saved the network you get success. but that does not mean you are connected. 

Basides I can't figure out how I can check if I am connected to the wifi or not on android 11 and above. I have implemented something. but again this is not the golden ticket. I will leave it at this for now. because we only need the `Network Request API` and not the suggestion API.

**Comment by SaltySpaghetti** [comment]
So now on which version of Android it works correctly?

**Comment by vanlooverenkoen** [comment]
It works to connect or save a network. The boolean that is returned simply does not work.

**Comment by SaltySpaghetti** [comment]
Ok, so it works like the older version. I want to clarify that I'm not trying to complain about your work, I'm just asking to understand the situation. Take your time

**Comment by vanlooverenkoen** [comment]
So right now the implementation contains the correct api's for each android OS. 

< android 10 should now return the correct boolean. Because I check if it is connected to the correct ssid (not yet tested, because I don't have an old android 10 device at the moment)
> android 10 can save a network & it connects to that network. but we can't figure out if we are really connected in code. because getting the ssid is deprecated since android 10. So we can't use that anymore and there is good alternative to check if we are connected.

**Comment by SaltySpaghetti** [comment]
I can test it tomorrow

**Comment by vanlooverenkoen** [comment]
Also: thanks one plus -> https://forums.oneplus.com/threads/crash-launching-android-settings-wifi_add_networks-intent.1353760/

**Comment by SaltySpaghetti** [comment]
I have OnePlus 6T and an 8T, lol
Anyways I've tested your commits on other devices that I don't own. 
When I posted [this](https://github.com/wonjerry/flutter_wifi_connector/pull/13#issuecomment-985585983) reply, my tests were on a Huawei with Android 10 and a Samsung with Android 11.

**Comment by Rodrigo-yuca** [comment]
@vanlooverenkoen I tested it directly from your branch and after connecting to the network, the app crashes but doesn't generate any logs, could you tell me if it's something internal on android? I'm using a samsung note 20 ultra 5g with android 11

**Comment by vanlooverenkoen** [comment]
@Rodrigo-yuca can you give me the example you used. Because the wifi API is very poorly integrated when not using Stock android. sadly

**Comment by Rodrigo-yuca** [comment]
@vanlooverenkoen  After connecting the screen freezes and I can't do anything until a dialog appears with the option to close app or wait.
below the adapted function of the example, and passed in a button onTap

> Future<void> _onConnectPressed() async {
    const ssid = 'Rodrigo 5G';
    const password = 'mypassword';
    await WifiConnector.connectToWifi(ssid: ssid, password: password, securityType: SecurityType.WPA2);
  }`

image
image

**Comment by vanlooverenkoen** [comment]
Do you see something in your logcat?

**Comment by Rodrigo-yuca** [comment]
@vanlooverenkoen  no, only this message in logcat or debug console

**Comment by vanlooverenkoen** [comment]
today I received our test device. so I can start again with testing and trying to get this working with the latest api's.

**Comment by vanlooverenkoen** [comment]
I got it working for our setup device. I will close this pull request and add feature per feature.

**Pull request closed without merging**
